// <auto-generated />
using System;
using JogosVintageWebApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JogosVintageWebApplication.Migrations
{
    [DbContext(typeof(JogosVintageWebApplicationContext))]
    [Migration("20230101175620_FinalFinal")]
    partial class FinalFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JogosVintageWebApplication.Models.Consolas", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("Descrição")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Processador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RAM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Saida")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Consolas");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Ano = 1983,
                            Descrição = "O Nintendo Entertainment System (NES, popularmente chamado de Nintendinho no Brasil) é um console de videogame de 8 bits lançado pela Nintendo na América do Norte, Europa, Ásia, Austrália e Brasil. Originalmente lançado no Japão em 1983 com o nome de Nintendo Family Computer",
                            Imagem = "lib\\img\\Consolas\\Console1.jpg",
                            Name = "NES",
                            Processador = "8 bits",
                            RAM = "2 KiB + memória RAM expandida (se presente no cartucho).",
                            Saida = "Modulador RF."
                        },
                        new
                        {
                            ID = 2,
                            Ano = 1988,
                            Descrição = "Consola de vídeo jogo de 16 bits, desenvolvido e comercializado pela Sega sendo um sucessor do Master System. O console foi lançado em 1988 no Japão como Mega Drive e em 1989 na América do Norte como Genesis.",
                            Imagem = "lib\\img\\Consolas\\Console2.jpg",
                            Name = "Mega Drive",
                            Processador = "16 bits",
                            RAM = "64KB",
                            Saida = "Modulador RF."
                        });
                });

            modelBuilder.Entity("JogosVintageWebApplication.Models.Jogos", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descrição")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idioma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plataforma")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Jogos");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Descrição = "Jogo eletrônico de plataforma desenvolvido pela Nintendo Research & Development 4 e publicado pela Nintendo para o Famicom em 1985 no Japão e para o Nintendo Entertainment System (NES) em 1985 e 1987 na América do Norte e Europa.",
                            Idioma = "Inglês",
                            Imagem = "lib\\img\\Jogos\\Jogo1.jpg",
                            Modelo = "NES",
                            Name = "Super Mario",
                            Plataforma = "Nintendo"
                        },
                        new
                        {
                            ID = 2,
                            Descrição = "Jogo eletrônico de beat 'em up que foi desenvolvido e publicado pela Sega para o Mega Drive. Foi lançado nos Estados Unidos em 31 de dezembro de 1990 e no Japão no dia 2 de agosto de 1991.",
                            Idioma = "Inglês",
                            Imagem = "lib\\img\\Jogos\\Jogo2.jpg",
                            Modelo = "Mega Drive",
                            Name = "Streets of Rage",
                            Plataforma = "Sega"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
